#local_backend: true

collections:
  - name: "docs"
    label: "Documentation"
    folder: "src/content/docs" # Direct connection to Starlight pages
    create: true
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "string", required: false }
      - label: "Template Layout"
        name: "template"
        widget: "hidden"
        options: ["doc", "splash"]
        default: "doc"
        required: true
      - { label: "Body Content", name: "body", widget: "markdown", required: true }

  - name: "cases"
    label: "Cases"
    folder: "src/content/docs/cases" # Direct connection to Starlight pages
    create: true
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "string", required: false }
      - label: "Template Layout"
        name: "template"
        widget: "hidden"
        options: ["doc", "splash"]
        default: "doc"
        required: true
      - { label: "Body Content", name: "body", widget: "markdown", required: true }

      

media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media

backend:
  name: github
  repo: mcoulson33/or-wiki-astro
  branch: main # Branch to update (optional; defaults to master)